# Generated by Django 5.2.1 on 2025-06-02 05:08

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='知識庫名稱')),
                ('summary', models.TextField(max_length=100, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='原始內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '知識庫',
                'verbose_name_plural': '知識庫',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_type', models.CharField(choices=[('custom', '自定義題目'), ('flashcard', '閃卡')], max_length=20, verbose_name='答題類型')),
                ('question_types', models.CharField(max_length=100, verbose_name='題目類型')),
                ('difficulty', models.CharField(max_length=20, verbose_name='難度')),
                ('total_questions', models.IntegerField(verbose_name='總題數')),
                ('current_question', models.IntegerField(default=0, verbose_name='當前題目索引')),
                ('questions_data', models.JSONField(default=list, verbose_name='題目資料')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='總分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('knowledge_bases', models.ManyToManyField(to='quiz.knowledgebase', verbose_name='使用的知識庫')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '答題會話',
                'verbose_name_plural': '答題會話',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoryQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_base_ids', models.CharField(max_length=200, verbose_name='知識庫ID組合')),
                ('question_hash', models.CharField(max_length=64, verbose_name='題目雜湊值')),
                ('question_data', models.JSONField(verbose_name='題目資料')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '歷史題目',
                'verbose_name_plural': '歷史題目',
                'indexes': [models.Index(fields=['user', 'knowledge_base_ids'], name='quiz_histor_user_id_799bda_idx')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='片段內容')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768, verbose_name='向量嵌入')),
                ('chunk_index', models.IntegerField(verbose_name='片段索引')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='quiz.knowledgebase', verbose_name='所屬知識庫')),
            ],
            options={
                'verbose_name': '知識片段',
                'verbose_name_plural': '知識片段',
                'indexes': [models.Index(fields=['knowledge_base', 'chunk_index'], name='quiz_knowle_knowled_f992a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.IntegerField(verbose_name='題目索引')),
                ('question_text', models.TextField(verbose_name='題目內容')),
                ('question_type', models.CharField(max_length=20, verbose_name='題目類型')),
                ('correct_answer', models.TextField(verbose_name='正確答案')),
                ('user_answer', models.TextField(verbose_name='使用者答案')),
                ('score', models.IntegerField(verbose_name='得分')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='回答時間')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizsession', verbose_name='答題會話')),
            ],
            options={
                'verbose_name': '題目回答',
                'verbose_name_plural': '題目回答',
                'unique_together': {('session', 'question_index')},
            },
        ),
    ]
